#%RAML 1.0
title: master-index api
version: 1
baseUri: https://system/master-index/entries{version}

types:
  search_entry:
    type: object
    properties: 
      key:
        type: string
        required: false
        minLength: 1
      kind:
        type: string
        required: false
        minLength: 1
      origin:
        type: string
        required: false
        minLength: 1
        
  search_entries:
    type: search_entry[] | search_entry
        
  nested_search_entries:
    type: search_entries[]
    
  directory_entry:
    type: object
    properties:
      key:
        type: string
        required: false
        minLength: 1
      kind:
        type: string
        required: false
        minLength: 1
      origin:
        type: string
        required: false
        minLength: 1
    
  directory:
    type: object
    properties: 
      id:
        type: string
        required: false
        minLength: 1
        example: "0"
      version:
        type: string
        required: false
        minLength: 1
        example: "1.0.0"
      kind:
        type: string
        required: false
        minLength: 1
        example: "person"
      entries: 
        type: directory_entry[]
        required: true
        
  directories:
    type: directory[]

/system/directory/v1/entries/{id}:
  uriParameters:
    id:
      type: string
  get:
    description: get a document by its id
    responses:
      200:
        body:
          application/json:
            type: directories
            example: [
              {
                "id": "0",
                "version": "1.0.0",
                "kind": "person",
                "entries": [
                  {
                    "key": "123",
                    "kind": "internal person identifier",
                    "origin": "comsas"
                  },
                  {
                    "key": "77929555",
                    "kind": "external interest identifier",
                    "origin": "comsas"
                  },
                  {
                    "key": "12345",
                    "kind": "internal interest identifier",
                    "origin": "comsas"
                  }
                ]
              }
            ]

/system/directory/v1/entries/search:
  post:
    description: Search directory entries
    queryParameters:
      offset:
        type: number
        required: false
        minimum: 0
      limit:
        type: number
        required: false
        minimum: 1
    body:
      application/json:
        type: nested_search_entries
        example: [
          {
            key: "123",
            kind: "internal person identifier"
          },
          [
            {
              key: "123",
              kind: "internal person identifier"
            },
            {
              key: "77929555",
              kind: "external interest identifier"
            }
            
          ]
        ]
    responses:
      200:
        body:
          application/json:
            type: directories
            example: [
              {
                "id": "0",
                "version": "1.0.0",
                "kind": "person",
                "entries": [
                  {
                    "key": "123",
                    "kind": "internal person identifier",
                    "origin": "comsas"
                  },
                  {
                    "key": "77929555",
                    "kind": "external interest identifier",
                    "origin": "comsas"
                  },
                  {
                    "key": "12345",
                    "kind": "internal interest identifier",
                    "origin": "comsas"
                  }
                ]
              }
            ]